name: Build
run-name: ${{ github.actor }} is building the app for ${{ github.ref }}
on:
  pull_request:
    branches: '**'
env:
  BUILD_DIR: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Project
        uses: actions/checkout@v3
      - name: Install meson
        run: ./scripts/install_meson.sh
      - name: Setup build dir
        run: ./scripts/setup_build.sh
      - name: Compile build
        run: ./scripts/compile_build.sh
