name: Linter
run-name: ${{ github.actor }} is linting for ${{ github.ref }}
on: [push]
jobs:
  linter:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "14"
