name: Unit Tests with Valgrind
run-name: ${{ github.actor }} is testing with valgrind the app for ${{ github.ref }}
on:
  push:
    branches: "**"
env:
  BUILD_DIR: build
jobs:
  valgrind-test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Project
        uses: actions/checkout@v3
      - name: Install valgrind
        run: sudo apt-get install valgrind -y
      - name: Install meson
        run: ./scripts/install_meson.sh
      - name: Setup build dir
        run: ./scripts/setup_build.sh
      - name: Run tests
        run: ./scripts/run_valgrind_tests.sh
